---
name: espbunker
synopsis: Haskell DSL for generating ESPHome YAML configurations
version: 1.0.1

license: MIT

ghc-options:
  - -fshow-warning-groups
  - -Werror
  - -Wall
  - -Wcompat
  - -Wcpp-undef
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fwrite-ide-info
  - -funbox-strict-fields
  - -flate-dmd-anal
  - -fno-omit-interface-pragmas

dependencies:
  - aeson
  - aeson-casing
  - base
  - base64-bytestring
  - containers
  - data-default
  - free
  - indexed
  - indexed-free
  - mtl
  - optparse-applicative
  - optparse-generic
  - relude
  - text
  - vector
  - yaml

library:
  source-dirs: ./src/

executables:
  espbunker:
    main: Main.hs
    source-dirs: app/
    dependencies:
      - espbunker
      - relude
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  espbunker-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - espbunker
      - typed-process
      - sydtest
      - sydtest-discover
      - path
