{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE NoImplicitPrelude #-}

module ESPBunker.DeviceClass where

import Data.Aeson
import Data.Aeson.Casing (snakeCase)
import Relude

data DeviceClass
  = DeviceClassBattery
  | DeviceClassConnectivity
  | DeviceClassDoor
  | DeviceClassGarageDoor
  | DeviceClassGas
  | DeviceClassHeat
  | DeviceClassLight
  | DeviceClassLock
  | DeviceClassMoisture
  | DeviceClassMotion
  | DeviceClassMoving
  | DeviceClassOccupancy
  | DeviceClassOpening
  | DeviceClassPlug
  | DeviceClassPower
  | DeviceClassPresence
  | DeviceClassProblem
  | DeviceClassSafety
  | DeviceClassSmoke
  | DeviceClassSound
  | DeviceClassVibration
  | DeviceClassWindow
  | DeviceClassWindowCovering
  | DeviceClassTemperature
  | DeviceClassHumidity
  | DeviceClassPressure
  | DeviceClassCurrent
  | DeviceClassEnergy
  | DeviceClassPowerFactor
  | DeviceClassFrequency
  | DeviceClassVoltage
  | DeviceClassSignalStrength
  | DeviceClassDataRate
  | DeviceClassDataSize
  | DeviceClassDistance
  | DeviceClassDuration
  | DeviceClassIlluminance
  | DeviceClassAccelG
  | DeviceClassAccelMs2
  | DeviceClassAltitude
  | DeviceClassArea
  | DeviceClassAqi
  | DeviceClassApparentPower
  | DeviceClassAtmosphericPressure
  | DeviceClassBaby
  | DeviceClassBaking
  | DeviceClassBeauty
  | DeviceClassBeverage
  | DeviceClassBoiler
  | DeviceClassBurglar
  | DeviceClassButton
  | DeviceClassCabinet
  | DeviceClassCarbonDioxide
  | DeviceClassCarbonMonoxide
  | DeviceClassCharger
  | DeviceClassCold
  | DeviceClassCommunication
  | DeviceClassConsumable
  | DeviceClassCooking
  | DeviceClassCounter
  | DeviceClassCurrentStage
  | DeviceClassDishwasher
  | DeviceClassDoorbell
  | DeviceClassDresser
  | DeviceClassDryer
  | DeviceClassEmergency
  | DeviceClassEmergencyCall
  | DeviceClassFan
  | DeviceClassFault
  | DeviceClassFilter
  | DeviceClassFire
  | DeviceClassFirmware
  | DeviceClassFlag
  | DeviceClassGarage
  | DeviceClassGasoline
  | DeviceClassGenerator
  | DeviceClassHvac
  | DeviceClassHazel
  | DeviceClassHealth
  | DeviceClassHeatCold
  | DeviceClassHelper
  | DeviceClassHolding
  | DeviceClassHood
  | DeviceClassHub
  | DeviceClassInverter
  | DeviceClassIrradiance
  | DeviceClassKeypad
  | DeviceClassLevel
  | DeviceClassLifeSafety
  | DeviceClassLighting
  | DeviceClassLinen
  | DeviceClassLockTight
  | DeviceClassMains
  | DeviceClassMedical
  | DeviceClassMode
  | DeviceClassMotionSensitivity
  | DeviceClassMovingRate
  | DeviceClassMower
  | DeviceClassMusic
  | DeviceClassNetwork
  | DeviceClassNight
  | DeviceClassNutrition
  | DeviceClassOil
  | DeviceClassOnline
  | DeviceClassOpeningLevel
  | DeviceClassOutlet
  | DeviceClassOxygen
  | DeviceClassPm1
  | DeviceClassPm10
  | DeviceClassPm25
  | DeviceClassParking
  | DeviceClassPeak
  | DeviceClassPerfume
  | DeviceClassPestControl
  | DeviceClassPh
  | DeviceClassPolice
  | DeviceClassPowerOutage
  | DeviceClassPowerSupply
  | DeviceClassPregnancy
  | DeviceClassPropane
  | DeviceClassRadiation
  | DeviceClassRadiator
  | DeviceClassRain
  | DeviceClassRefrigerator
  | DeviceClassRemainder
  | DeviceClassRemote
  | DeviceClassRfid
  | DeviceClassSour
  | DeviceClassSalt
  | DeviceClassShampoo
  | DeviceClassShelfLife
  | DeviceClassShopping
  | DeviceClassShort
  | DeviceClassShower
  | DeviceClassSiren
  | DeviceClassSmokeAlarm
  | DeviceClassSoap
  | DeviceClassSoda
  | DeviceClassSolar
  | DeviceClassShutter
  | DeviceClassSoundPressure
  | DeviceClassSpill
  | DeviceClassStale
  | DeviceClassState
  | DeviceClassStatus
  | DeviceClassSulphurDioxide
  | DeviceClassSystem
  | DeviceClassTare
  | DeviceClassTechnical
  | DeviceClassTamper
  | DeviceClassTargetTemperature
  | DeviceClassTask
  | DeviceClassTarget
  | DeviceClassTemperatureAmbient
  | DeviceClassThermalZone
  | DeviceClassTime
  | DeviceClassTimer
  | DeviceClassTobacco
  | DeviceClassToner
  | DeviceClassTorque
  | DeviceClassTransit
  | DeviceClassTreble
  | DeviceClassTuner
  | DeviceClassTv
  | DeviceClassUltraviolet
  | DeviceClassUnitless
  | DeviceClassUnlock
  | DeviceClassUpdate
  | DeviceClassUser
  | DeviceClassUtility
  | DeviceClassVolatileOrganicCompounds
  | DeviceClassVolatileOrganicCompoundsParts
  | DeviceClassVolume
  | DeviceClassVolumeFlowRate
  | DeviceClassWater
  | DeviceClassWeight
  | DeviceClassWifi
  | DeviceClassWine
  | DeviceClassWinter
  | DeviceClassWok
  | DeviceClassWork
  | DeviceClassWasher
  | DeviceClassXyCoordinate
  | DeviceClassYeast
  | DeviceClassOther Text
  deriving (Show, Eq, Generic)

instance ToJSON DeviceClass where
  toJSON = String . toText . snakeCase . drop (length "DeviceClass") . show
